package domain

import (
	"time"

	"github.com/google/uuid"
)

// Signal represents a trading signal generated by the AI
type Signal struct {
	ID           uuid.UUID `json:"id"`
	Symbol       string    `json:"symbol"`
	Type         string    `json:"type"`
	EntryPrice   float64   `json:"entry_price"`
	SLPrice      float64   `json:"sl_price"`
	TPPrice      float64   `json:"tp_price"`
	Confidence   int       `json:"confidence"`
	Reasoning    string    `json:"reasoning"`
	Status       string    `json:"status"`
	ReviewResult *string   `json:"review_result,omitempty"`
	ReviewPnL    *float64  `json:"review_pnl,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
}

// SignalType constants
const (
	SignalLong  = "LONG"
	SignalShort = "SHORT"
)

// SignalStatus constants
const (
	StatusPending  = "PENDING"
	StatusExecuted = "EXECUTED"
	StatusRejected = "REJECTED"
)

// ReviewResult constants
const (
	ReviewWin      = "WIN"
	ReviewLoss     = "LOSS"
	ReviewFloating = "FLOATING"
)

// TradeParams contains the trade parameters from AI analysis
type TradeParams struct {
	EntryPrice        float64 `json:"entry_price"`
	StopLoss          float64 `json:"stop_loss"`
	TakeProfit        float64 `json:"take_profit"`
	SuggestedLeverage int     `json:"suggested_leverage"`
	PositionSizeUSDT  float64 `json:"position_size_usdt"`
}

// AISignalResponse represents the response from Python AI engine
type AISignalResponse struct {
	Symbol             string       `json:"symbol"`
	FinalSignal        string       `json:"final_signal"`
	CombinedConfidence int          `json:"combined_confidence"`
	Agreement          bool         `json:"agreement"`
	Recommendation     string       `json:"recommendation"`
	LogicReasoning     string       `json:"logic_reasoning"`
	VisionAnalysis     string       `json:"vision_analysis"`
	TradeParams        *TradeParams `json:"trade_params"`
}
