package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// ScreenerMetrics holds the quantitative metrics snapshot from screener
type ScreenerMetrics struct {
	ADX        float64 `json:"adx"`
	VolZScore  float64 `json:"vol_z_score"`
	KER        float64 `json:"ker"` // Kaufman Efficiency Ratio
	IsSqueeze  bool    `json:"is_squeeze"`
	Score      float64 `json:"score"`
	VolRatio   float64 `json:"vol_ratio"`
	ATRPercent float64 `json:"atr_pct"`
}

// Signal represents a trading signal generated by the AI
type Signal struct {
	ID              uuid.UUID        `json:"id"`
	Symbol          string           `json:"symbol"`
	Type            string           `json:"type"`
	EntryPrice      float64          `json:"entry_price"`
	SLPrice         float64          `json:"sl_price"`
	TPPrice         float64          `json:"tp_price"`
	Confidence      int              `json:"confidence"`
	Reasoning       string           `json:"reasoning"`
	EntryReasoning  string           `json:"entry_reasoning"` // New field for Math/Entry Logic
	Status          string           `json:"status"`
	ReviewResult    *string          `json:"review_result,omitempty"`
	ReviewPnL       *float64         `json:"review_pnl,omitempty"`
	ScreenerMetrics *ScreenerMetrics `json:"screener_metrics,omitempty"`
	CreatedAt       time.Time        `json:"created_at"`
}

// SignalType constants
const (
	SignalLong  = "LONG"
	SignalShort = "SHORT"
)

// SignalStatus constants
const (
	StatusPending  = "PENDING"
	StatusExecuted = "EXECUTED"
	StatusRejected = "REJECTED"
	StatusFailed   = "FAILED"
)

// ReviewResult constants
const (
	ReviewWin      = "WIN"
	ReviewLoss     = "LOSS"
	ReviewFloating = "FLOATING"
)

// TradeParams contains the trade parameters from AI analysis
type TradeParams struct {
	EntryPrice        float64 `json:"entry_price"`
	StopLoss          float64 `json:"stop_loss"`
	TakeProfit        float64 `json:"take_profit"`
	SuggestedLeverage int     `json:"suggested_leverage"`
	PositionSizeUSDT  float64 `json:"position_size_usdt"`
}

// AISignalResponse represents the response from Python AI engine
type AISignalResponse struct {
	Symbol             string       `json:"symbol"`
	FinalSignal        string       `json:"final_signal"`
	CombinedConfidence int          `json:"combined_confidence"`
	Agreement          bool         `json:"agreement"`
	Recommendation     string       `json:"recommendation"`
	LogicReasoning     string       `json:"logic_reasoning"`
	VisionAnalysis     string       `json:"vision_analysis"`
	TradeParams        *TradeParams `json:"trade_params"`
	EntryParams        *struct {
		Reasoning string `json:"reasoning"`
	} `json:"entry_params"`
	ScreenerMetrics map[string]interface{} `json:"screener_metrics,omitempty"` // ML metrics for feedback loop
}

// SignalRepository defines the interface for signal data operations
type SignalRepository interface {
	// Save saves a new signal to the database
	Save(ctx context.Context, signal *Signal) error

	// GetRecent retrieves the most recent signals
	GetRecent(ctx context.Context, limit int) ([]*Signal, error)

	// GetByID retrieves a signal by its ID
	GetByID(ctx context.Context, id uuid.UUID) (*Signal, error)

	// GetBySymbol retrieves signals for a specific symbol
	GetBySymbol(ctx context.Context, symbol string, limit int) ([]*Signal, error)

	// UpdateStatus updates the status of a signal
	UpdateStatus(ctx context.Context, id uuid.UUID, status string) error

	// UpdateReviewStatus updates the review result and PnL of a signal
	UpdateReviewStatus(ctx context.Context, id uuid.UUID, result string, pnl *float64) error

	// GetPendingSignals retrieves signals that are pending review (older than specified minutes)
	GetPendingSignals(ctx context.Context, olderThanMinutes int) ([]*Signal, error)
}
